### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by aekazitt** [giantpoplar/gd#1]
Seems from the Libraries involved, this project is aimed at Chinese Sentence Feature Extraction correct? But only the preprocess part is done. 

Would be great to see it continue. Please let me know if I can help contribute to it as well.

Cheers,
Sitt

**Comment by giantpoplar** [comment]
Thank you for your attention. I'm sorry that this project is no longer matained. 
I have uploaded the backend part(not well designed) of the whole project just for the sake of completeness.
